version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
  gh: circleci/github-cli@1.0
jobs:
  build_login_workflow:
    working_directory: ~/login-workflow
    docker:
      - image: circleci/node:14.17-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "login-workflow/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            cd login-workflow
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "login-workflow/yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            cd login-workflow
            yarn prettier:check
      - run:
          name: Set Max Memory
          command: NODE_OPTIONS=--max_old_space_size=2048
      - run:
          name: Lint
          command: |
            cd login-workflow
            yarn lint
      - run:
          name: Tests
          command: |
            cd login-workflow
            yarn test --maxWorkers=2 --coverage --watchAll=false
      - run:
          name: Build
          command: |
            cd login-workflow
            yarn build
      - persist_to_workspace:
          root: .
          paths:
            - login-workflow/lib
            - login-workflow/coverage
  coverage_report:
    working_directory: ~/react-native-workflows
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - codecov/upload:
          file: "./login-workflow/coverage/clover.xml"
          token: 6bd0adf7-ec9c-43ad-b1e9-dd71013923f2

  publish_login_workflow:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish @brightlayer-ui/react-native-auth-workflow
          command: |
            cd login-workflow && yarn publish:package -b $CIRCLE_BRANCH

  gh_tag_login_workflow:
    docker:
      - image: circleci/node:12.16.3-browsers
    steps:
      - checkout
      - gh/setup
      - run:
          name: Tag @brightlayer-ui/react-native-auth-workflow
          command: |
            cd login-workflow
            yarn tag-package -b $CIRCLE_BRANCH -s -react-native-auth-workflow

workflows:
  version: 2
  react_native_workflows:
    jobs:
      - build_login_workflow
      - publish_login_workflow:
          requires:
            - build_login_workflow
          filters:
            branches:
              only:
                - master
                - dev
      - gh_tag_login_workflow:
          requires:
            - publish_login_workflow
          filters:
            branches:
              only:
                - master
      - coverage_report:
          requires:
            - build_login_workflow
          filters:
            branches:
              only:
                - master
