version: 2
jobs:
    build_library:
        docker:
            - image: circleci/node:12.9.1-browsers
        working_directory: ~/login-workflow
        environment:
            - MASTER_BRANCH: master
            - DEV_BRANCH: dev
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ checksum "login-workflow/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd login-workflow
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - node_modules
                  key: v2-dependencies-{{ checksum "login-workflow/yarn.lock" }}
            - run:
                  name: Lint
                  command: |
                      cd login-workflow
                      yarn lint
            - run:
                  name: Prettier Check
                  command: |
                      cd login-workflow
                      yarn prettier --check
            - run:
                  name: Tests
                  command: |
                      yarn test
            - run:
                  name: Build
                  command: |
                      yarn build
