# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Yarn@3
  inputs:
    arguments: 'install --frozen-lockfile'

- task: Yarn@3
  inputs:
    arguments: 'prettier:check'
  continueOnError: true
  displayName: 'Prettier Check'

- task: Yarn@3
  inputs:
    arguments: 'lint'
  continueOnError: true
  displayName: 'Lint Free'

- task: Yarn@3
  inputs:
    arguments: 'typescript'
  continueOnError: true
  displayName: 'Typescript Compile'

- task: Yarn@3
  inputs:
    arguments: 'test --ci --reporters=default --reporters=jest-junit --coverage --coverageReporters=cobertura'
  displayName: 'Test with Jest'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Module Unit Tests'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'
    # pathToSources: '$(System.DefaultWorkingDirectory)'
    # reportDirectory: 'coverage/lcov-report/'
    failIfCoverageEmpty: true